---

- name: Start swarm agent
  docker:
    name: swarm-node
    image: swarm
    command: "join --addr={{ docker_swarm_node_ip }}:{{ docker_port }} token://{{ docker_swarm_cluster_id }}"
  when: not docker_swarm_master

- name: Start swarm master
  docker:
    name: swarm-master
    image: swarm
    ports: "{{ docker_port }}:{{ docker_port }}"
    command: "manage token://{{ docker_swarm_cluster_id }}"
    env:
      SERVICE_ID: swarm-master
  when: docker_swarm_master
